@host=https://localhost:7076

POST {{host}}/clients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDYXJSZW50YWwuRG9tYWluLlVzZXJBZ2dyZWdhdGUuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJXYWx0ZXIiLCJmYW1pbHlfbmFtZSI6IkFycm95byIsImp0aSI6ImZmMDAxNWVmLWM1ZWUtNGE0NC1hN2NjLTAxZDYzNzJkMjYxZiIsInVuaXF1ZV9uYW1lIjoiQ2FyUmVudGFsLkRvbWFpbi5Vc2VyQWdncmVnYXRlLlZhbHVlT2JqZWN0cy5Vc2VySWQiLCJleHAiOjE2NzgzMzI4NzksImlzcyI6IlJlbnRhbENhciIsImF1ZCI6IlJlbnRhbENhciJ9.cgHEz_m6tE-v1pKk0G7vbNO8CfNd_vtup3GagO738bA
Content-Type: application/json

{
  "firstName": "FirstNameTest",
  "middleName": "MiddleNameTest",
  "lastName": "LastNameTest",
  "socialNumberId": "FK15658569"
}