@host=https://localhost:7076

GET {{host}}/rentals/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OGQ2MjgwNC1mNTE0LTRiZGQtOTI3ZS1jNzUxMmJhN2I2YWEiLCJnaXZlbl9uYW1lIjoiV2FsdGVyIiwiZmFtaWx5X25hbWUiOiJBcnJveW8iLCJqdGkiOiI3YWE4YTQ2Ni1iZTg1LTQxYWUtOWY2Zi1mNTJiZGQ1YWQ1Y2YiLCJ1bmlxdWVfbmFtZSI6IjU4ZDYyODA0LWY1MTQtNGJkZC05MjdlLWM3NTEyYmE3YjZhYSIsImV4cCI6MTY3Nzg3Mzc2NywiaXNzIjoiUmVudGFsQ2FyIiwiYXVkIjoiUmVudGFsQ2FyIn0.iRaLPkMH3Y7z4beF-7lRj5Ehd1KDj8ju5pO1-XDskWo